### ISSUE TITLE
Plugin is broken in 1.19.

### ISSUE THREAD

**Issue by zohfur** [MarioFinale/VillagerSaver#19]
Plugin does not work or save villagers in 1.19, if it's not too much trouble an update would be appreciated. Love your plugin.

```
[21:39:43 ERROR]: Could not pass event EntityDamageByEntityEvent to VillagerSaver v1.2.5
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R2/entity/CraftVillager
        at cl.mariofinale.VillagerSaver_Listener.handleSpawnZombieVillager(VillagerSaver_Listener.java:34) ~[VillagerSaver (1).jar:?]
        at cl.mariofinale.VillagerSaver_Listener.onEntityDamageByEntity(VillagerSaver_Listener.java:29) ~[VillagerSaver (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-10]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[paper-1.19.jar:git-Paper-10]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1151) ~[paper-1.19.jar:git-Paper-10]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1010) ~[paper-1.19.jar:git-Paper-10]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:962) ~[paper-1.19.jar:git-Paper-10]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1185) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2097) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1369) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1605) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:364) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:130) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:121) ~[?:?]
        at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:151) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:142) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:867) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3307) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:634) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:269) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2949) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:239) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:898) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-10]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R2.entity.CraftVillager
        ... 41 more
[21:39:43 INFO]: Villager EntityVillager['Villager'/115918, uuid='beee08e0-053b-42ec-bad9-de935af37907', l='ServerLevel[world]', x=-1390.66, y=56.31, z=-844.30, cpos=[-87, -53], tl=1488891, v=true] died, message: 'Villager was slain by Zombie'
```

**Comment by MarioFinale** [comment]
@zxopher Updated to [1.19](https://github.com/MarioFinale/VillagerSaver/releases/tag/1.3.1) 🙂
